
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WeSon8840
 */
public class FamilyBudgeTGUI extends javax.swing.JFrame {

    /**
     * Creates new form FamilyBudgeTGUI
     */
    public FamilyBudgeTGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        FirstLabel = new javax.swing.JLabel();
        HousingLabel = new javax.swing.JLabel();
        TransportationLabel = new javax.swing.JLabel();
        LifeLabel = new javax.swing.JLabel();
        SavingLbel = new javax.swing.JLabel();
        IncomeLabel = new javax.swing.JLabel();
        HousingInput = new javax.swing.JTextField();
        TransportationInput = new javax.swing.JTextField();
        LifeInput = new javax.swing.JTextField();
        SavingInput = new javax.swing.JTextField();
        IncomeInput = new javax.swing.JTextField();
        EnterButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        MonthlySpedningLabel = new javax.swing.JLabel();
        housinglabel = new javax.swing.JLabel();
        transportationLabel = new javax.swing.JLabel();
        lifeLabel = new javax.swing.JLabel();
        savingLabel = new javax.swing.JLabel();
        HousingOutput = new javax.swing.JLabel();
        TransportationOutput = new javax.swing.JLabel();
        LifeOutput = new javax.swing.JLabel();
        SavingsOutput = new javax.swing.JLabel();
        Housingbar = new javax.swing.JLabel();
        Transportationbar = new javax.swing.JLabel();
        LifeBar = new javax.swing.JLabel();
        Savingbar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        housingoutput = new javax.swing.JLabel();
        trasportationoutput = new javax.swing.JLabel();
        lifeoutput = new javax.swing.JLabel();
        savingsoutput = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TitleLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 28)); // NOI18N
        TitleLabel.setText("Family Budget");

        FirstLabel.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        FirstLabel.setText("Enter the amount you spend in each category per month.");

        HousingLabel.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        HousingLabel.setText("Housing:");

        TransportationLabel.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        TransportationLabel.setText("Transportation:");

        LifeLabel.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        LifeLabel.setText("Life:");

        SavingLbel.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        SavingLbel.setText("Savings:");

        IncomeLabel.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        IncomeLabel.setText("Enter your net monthly income:");

        HousingInput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        HousingInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HousingInputActionPerformed(evt);
            }
        });

        TransportationInput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N

        LifeInput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        LifeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LifeInputActionPerformed(evt);
            }
        });

        SavingInput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        SavingInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingInputActionPerformed(evt);
            }
        });

        IncomeInput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        IncomeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomeInputActionPerformed(evt);
            }
        });

        EnterButton.setFont(new java.awt.Font("Lint McCree Intl BB", 0, 12)); // NOI18N
        EnterButton.setText("Calculate");
        EnterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterButtonMouseClicked(evt);
            }
        });
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IncomeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(IncomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FirstLabel)
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TransportationLabel)
                            .addComponent(HousingLabel)
                            .addComponent(LifeLabel)
                            .addComponent(SavingLbel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TransportationInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(LifeInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SavingInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HousingInput))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EnterButton)
                        .addGap(42, 42, 42))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(TitleLabel)
                .addGap(4, 4, 4)
                .addComponent(FirstLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HousingInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HousingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TransportationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TransportationLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LifeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LifeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SavingInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SavingLbel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IncomeLabel)
                            .addComponent(IncomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EnterButton)
                        .addGap(69, 69, 69))))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        MonthlySpedningLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 22)); // NOI18N
        MonthlySpedningLabel.setText("Monthly Spending");

        housinglabel.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        housinglabel.setText("Housing:");

        transportationLabel.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        transportationLabel.setText("Transportation:");

        lifeLabel.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        lifeLabel.setText("Life:");

        savingLabel.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        savingLabel.setText("Savings:");

        HousingOutput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        HousingOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TransportationOutput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        TransportationOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LifeOutput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        LifeOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SavingsOutput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        SavingsOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Housingbar.setBackground(new java.awt.Color(255, 51, 51));
        Housingbar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Housingbar.setText(" ");
        Housingbar.setOpaque(true);

        Transportationbar.setBackground(new java.awt.Color(255, 51, 255));
        Transportationbar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Transportationbar.setText(" ");
        Transportationbar.setOpaque(true);

        LifeBar.setBackground(new java.awt.Color(0, 102, 255));
        LifeBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LifeBar.setText(" ");
        LifeBar.setOpaque(true);

        Savingbar.setBackground(new java.awt.Color(108, 15, 201));
        Savingbar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Savingbar.setText(" ");
        Savingbar.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(MonthlySpedningLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(transportationLabel)
                                    .addComponent(housinglabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lifeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(savingLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(HousingOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addComponent(LifeOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(SavingsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TransportationOutput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Housingbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Transportationbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LifeBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Savingbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MonthlySpedningLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HousingOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(housinglabel)
                    .addComponent(Housingbar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TransportationOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportationLabel)
                    .addComponent(Transportationbar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LifeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lifeLabel)
                    .addComponent(LifeBar))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SavingsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Savingbar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        housingoutput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        housingoutput.setText(" ");

        trasportationoutput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        trasportationoutput.setText(" ");

        lifeoutput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        lifeoutput.setText(" ");

        savingsoutput.setFont(new java.awt.Font("SouvenirItcTEELig", 0, 14)); // NOI18N
        savingsoutput.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(housingoutput, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(trasportationoutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lifeoutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(savingsoutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(housingoutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trasportationoutput)
                .addGap(13, 13, 13)
                .addComponent(lifeoutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savingsoutput)
                .addGap(23, 23, 23))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HousingInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HousingInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HousingInputActionPerformed

    private void LifeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LifeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LifeInputActionPerformed

    private void SavingInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavingInputActionPerformed

    private void IncomeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncomeInputActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        String housing = HousingInput.getText();
        double h = Double.parseDouble(housing);
        
        String transportation = TransportationInput.getText();
        double t = Double.parseDouble(transportation);
        
        String life = LifeInput.getText();
        double l = Double.parseDouble(life);
        
        String saving = SavingInput.getText();
        double s = Double.parseDouble(saving);
        
        String income = IncomeInput.getText();
        double i = Double.parseDouble(income);
        
        double hp,tp,lp,sp;
        hp = h/i * 100;
        hp = (int)Math.round(hp);
        HousingOutput.setText("" + hp + "%");
        
        tp = t/i * 100;
        tp = (int)Math.round(tp);
        TransportationOutput.setText("" + tp + "%");
        
        lp = l/i * 100;
        lp = (int)Math.round(lp);
        LifeOutput.setText("" + lp + "%");
        
        sp = s/i * 100;
        sp = (int)Math.round(sp);
        SavingsOutput.setText("" + sp + "%");
        
        if (hp <= 35){
            housingoutput.setText("Good job! Your speding on housing is okay!");
        }
        else if (hp > 35){
            housingoutput.setText("Warning! You are spending too much on housing!");
        }
        
        if (hp <= 15){
            trasportationoutput.setText("Good job! Your speding on transportation is okay!");
        }
        else if (hp > 15){
            trasportationoutput.setText("Warning! You are spending too much on transportation!");
        }
        
        if (hp <= 25){
            lifeoutput.setText("Good job! Your speding on life is okay!");
        }
        else if (hp > 25){
            lifeoutput.setText("Warning! You are spending too much on life!");
        }
        
        if (hp >= 10){
            savingsoutput.setText("Good job! Your are putting enough money into savings!");
        }
        else if (hp < 10){
            savingsoutput.setText("Warning! You need to put more money money into savings!");
        }
        
        String Housing = " ";
        for (int HOUSING = 0; HOUSING <=hp; HOUSING++){
            Housingbar.setText(Housingbar.getText() + " ");
        }
        
         String Transportation = " ";
        for (int TRANSPORTATION = 0; TRANSPORTATION <=hp; TRANSPORTATION++){
            Transportationbar.setText(Transportationbar.getText() + " ");
        }
        
        String Life = " ";
        for (int LIFE = 0; LIFE <=hp; LIFE++){
            LifeBar.setText(LifeBar.getText() + " ");
        }
        
        String Saving = " ";
        for (int SAVING = 0; SAVING <=hp; SAVING++){
            Savingbar.setText(Savingbar.getText() + " ");
        }
          
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void EnterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterButtonMouseClicked
        EnterButton.setForeground(Color.gray);
    }//GEN-LAST:event_EnterButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamilyBudgeTGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamilyBudgeTGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamilyBudgeTGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamilyBudgeTGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamilyBudgeTGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterButton;
    private javax.swing.JLabel FirstLabel;
    private javax.swing.JTextField HousingInput;
    private javax.swing.JLabel HousingLabel;
    private javax.swing.JLabel HousingOutput;
    private javax.swing.JLabel Housingbar;
    private javax.swing.JTextField IncomeInput;
    private javax.swing.JLabel IncomeLabel;
    private javax.swing.JLabel LifeBar;
    private javax.swing.JTextField LifeInput;
    private javax.swing.JLabel LifeLabel;
    private javax.swing.JLabel LifeOutput;
    private javax.swing.JLabel MonthlySpedningLabel;
    private javax.swing.JTextField SavingInput;
    private javax.swing.JLabel SavingLbel;
    private javax.swing.JLabel Savingbar;
    private javax.swing.JLabel SavingsOutput;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField TransportationInput;
    private javax.swing.JLabel TransportationLabel;
    private javax.swing.JLabel TransportationOutput;
    private javax.swing.JLabel Transportationbar;
    private javax.swing.JLabel housinglabel;
    private javax.swing.JLabel housingoutput;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lifeLabel;
    private javax.swing.JLabel lifeoutput;
    private javax.swing.JLabel savingLabel;
    private javax.swing.JLabel savingsoutput;
    private javax.swing.JLabel transportationLabel;
    private javax.swing.JLabel trasportationoutput;
    // End of variables declaration//GEN-END:variables
}
